# Generated by Django 4.2.6 on 2023-11-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0008_alter_favoriterecipe_options_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="favoriterecipe",
            constraint=models.UniqueConstraint(
                fields=("user", "recipe"), name="check_favorite_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="shoppingcart",
            constraint=models.UniqueConstraint(
                fields=("user", "recipe"), name="check_shopping_cart_unique"
            ),
        ),
    ]
