# Generated by Django 4.2.6 on 2023-11-09 06:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0009_favoriterecipe_check_favorite_unique_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="amount",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Amount must be at least 1."
                    ),
                    django.core.validators.MaxValueValidator(
                        1440, message="Amount must be at most 1111."
                    ),
                ],
                verbose_name="Amount",
            ),
        ),
    ]
