# Generated by Django 3.2 on 2024-01-30 03:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_recipeingredient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='Input the total cooking time in minutes.', validators=[django.core.validators.MinValueValidator(1, message='Must be at least 1.'), django.core.validators.MaxValueValidator(32000, message='Cannot be greater than 32000')], verbose_name='Cooking time'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Must be at least 1.'), django.core.validators.MaxValueValidator(32000, message='Cannot be greater than 32000')], verbose_name='Amount'),
        ),
    ]
